  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: apps
    namespace: argocd
  spec:
    rules:
      - host: localhost
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    number: 80
