#require 'securerandom'
#TOKEN = SecureRandom.hex(16)
TOKEN = "42"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |vm|
    vm.memory = "1024"
    vm.cpus   = 1
  end

  config.vm.define "amejiaS" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.hostname = "amejiaS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server --token=#{TOKEN} \
          --tls-san=192.168.56.110 \
          --bind-address=0.0.0.0 \
          --node-ip=192.168.56.110 \
          --advertise-address=192.168.56.110" \
        sh -

      sed -i 's|127.0.0.1:6443|192.168.56.110:6443|g' /etc/rancher/k3s/k3s.yaml

      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/
      chown vagrant:vagrant /home/vagrant/k3s.yaml
  SHELL
  end

  config.vm.define "samusancSW" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "samusancSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN=#{TOKEN} \
        sh -s - agent
    SHELL
  end 
end
