apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: andres-cluster
servers: 1
agents: 1
options:
  k3s:
    extraArgs:
      - arg: "--no-deploy=traefik"
        nodeFilters:
          - "server:*"
ports:
  - port: "8080:80"
